export const iocToAlpha2: Record<string, string> = {
  'GBR': 'gb',
  'ESP': 'es',
  'USA': 'us',
  'GER': 'de',
  'AUT': 'at',
  'TPE': 'tw',
  'PHI': 'ph',
  'ALB': 'al',
  'GRE': 'gr',
  'SGP': 'sg',
  'POL': 'pl',
  'NED': 'nl',
  'CHN': 'cn',
  'JPN': 'jp',
  'BIH': 'ba',
  'FIN': 'fi',
  'CAN': 'ca',
  'VIE': 'vn',
  'KUW': 'kw',
  'LTU': 'lt',
  'HKG': 'hk',
  'HUN': 'hu',
  'SRB': 'rs',
  'FRA': 'fr',
  'ITA': 'it',
  'RSA': 'za',
  'AUS': 'au',
  'NZL': 'nz',
  'BRA': 'br',
  'ARG': 'ar',
  'MEX': 'mx',
  'KOR': 'kr',
  'INA': 'id',
  'MAS': 'my',
  'THA': 'th',
  'IND': 'in',
  'PAK': 'pk',
  'EGY': 'eg',
  'MAR': 'ma',
  'NGR': 'ng',
  'KEN': 'ke',
  'JAM': 'jm',
  'CUB': 'cu',
  'COL': 'co',
  'VEN': 've',
  'CHI': 'cl',
  'PER': 'pe',
  'URU': 'uy',
  'PAR': 'py',
  'ECU': 'ec',
  'BOL': 'bo',
  'CZE': 'cz',
  'SVK': 'sk',
  'ZAM': 'zm',
  'ZIM': 'zw'
};

export function getFlagUrl(ioc: string): string | null {
  const alpha2 = iocToAlpha2[ioc.toUpperCase()];
  if (!alpha2) return null;
  return `https://flagcdn.com/w40/${alpha2}.png`;
}
